#!/usr/bin/env node
/**
 * Bundles css/src/*.css into a single css/app.css and stamps every HTML
 * reference with a content hash so a deploy can never serve a stale
 * stylesheet from cache.
 *
 *   node tools/build.mjs [--minify] [--check] [--watch]
 *
 * --check exits non-zero when the committed output is out of date, which is
 * what CI uses to keep the built file honest.
 */

import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile, watch } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC_DIR = path.join(ROOT, 'css', 'src');
const OUT_FILE = path.join(ROOT, 'css', 'app.css');

const args = new Set(process.argv.slice(2));
const MINIFY = args.has('--minify');
const CHECK = args.has('--check');
const WATCH = args.has('--watch');

/** Strips comments and redundant whitespace without touching string literals. */
function minify(css) {
  return css
    .replace(/\/\*[\s\S]*?\*\//g, '')
    .replace(/\s*([{}:;,>~+])\s*/g, '$1')
    .replace(/;}/g, '}')
    .replace(/\s+/g, ' ')
    .trim();
}

async function bundle() {
  const files = (await readdir(SRC_DIR)).filter((f) => f.endsWith('.css')).sort();
  if (!files.length) throw new Error(`No stylesheets found in ${SRC_DIR}`);

  const parts = [];
  for (const file of files) {
    const css = await readFile(path.join(SRC_DIR, file), 'utf8');
    parts.push(MINIFY ? minify(css) : `/* >>> ${file} */\n${css.trim()}\n`);
  }

  const banner = '/* DigiStore design system — generated by tools/build.mjs. Edit css/src/*.css. */\n';
  const css = MINIFY ? banner + parts.join('') : banner + '\n' + parts.join('\n');
  const hash = createHash('sha256').update(css).digest('hex').slice(0, 8);
  return { css, hash, files };
}

/** Rewrites `./css/app.css?v=…` in every page so the hash always matches. */
async function stampHtml(hash) {
  const entries = await readdir(ROOT, { withFileTypes: true });
  const pages = entries.filter((e) => e.isFile() && e.name.endsWith('.html')).map((e) => e.name);
  const changed = [];

  for (const page of pages) {
    const file = path.join(ROOT, page);
    const html = await readFile(file, 'utf8');
    const next = html.replace(
      /(href="\.\/css\/app\.css)(\?v=[a-f0-9]+)?(")/g,
      `$1?v=${hash}$3`,
    );
    if (next !== html) {
      if (!CHECK) await writeFile(file, next);
      changed.push(page);
    }
  }
  return changed;
}

async function run() {
  const { css, hash, files } = await bundle();
  const previous = await readFile(OUT_FILE, 'utf8').catch(() => null);
  const stale = previous !== css;

  if (CHECK) {
    const drifted = await stampHtml(hash);
    if (stale || drifted.length) {
      console.error('css/app.css is out of date. Run: npm run build');
      if (drifted.length) console.error(`  stale cache stamp in: ${drifted.join(', ')}`);
      process.exitCode = 1;
      return;
    }
    console.log(`css/app.css is current (${files.length} sources, build ${hash}).`);
    return;
  }

  if (stale) await writeFile(OUT_FILE, css);
  const stamped = await stampHtml(hash);
  const kb = (Buffer.byteLength(css) / 1024).toFixed(1);
  console.log(
    `css/app.css ${stale ? 'rebuilt' : 'unchanged'} — ${files.length} sources, ${kb} kB, build ${hash}` +
      (stamped.length ? `; stamped ${stamped.length} page(s)` : ''),
  );
}

await run();

if (WATCH) {
  console.log('Watching css/src for changes. Ctrl+C to stop.');
  let queued = null;
  for await (const _event of watch(SRC_DIR)) {
    clearTimeout(queued);
    queued = setTimeout(() => run().catch((err) => console.error(err.message)), 60);
  }
}
